name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Prepare release folder
        run: |
          mkdir -Force release | Out-Null
          cp chromedriver.exe release/
          cp config.json release/
          cp links.txt release/
          cp README.md release/

      - name: Build
        run: go build -o release/screenshoter.exe

      - name: Create clean ZIP
        run: |
          $files = @(
            'release\screenshoter.exe',
            'release\chromedriver.exe',
            'release\config.json',
            'release\links.txt',
            'release\README.md'
          )
          Compress-Archive -Path $files -DestinationPath .\release\screenshoter.zip

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: release/screenshoter.zip